'''
1 2 3 4 5 6 7 8 9 
N S W E 

1N 2S 3W 4E 5N 6S 7W 8E 




'''

class CyclicIterator:
	def __init__(self,lst):
	    self.lst=lst
	    self.i=0
	    
    def __next__(self):
    	result = self.lst[self.i % len(self.lst)]
    	self.i+=1;
    	return result;
    	
    def __iter__(self):
        return self

cyc=CyclicIterator('NSWERT')

for _ in range(10):
    print(next(cyc))    	

class CyclicIterator:
	def __init__(self,lst,length):
	    self.lst=lst
	    self.i=0
	    self.length=length
	    
    def __next__(self):
    	if self.i > self.length:
    		return StopIteration
    	else:
    		result = self.lst[self.i % len(self.lst)]
    	    self.i+=1;
    	    return result;
    	
    def __iter__(self):
        return self

cyc=CyclicIterator('NSWERT',15)

numbers = range(10)
list(nunbers);


iter_cycl= CyclicIterator('NSWERT')   
for item in zip(list(numbers),iter_cycl):
	print("item",item);

[[1,'N'],[2,'S'],[3,'E'],[4,'W']]

number=[i+next(iter_cycl) for i in range(1,11)];
print(number);
'''
1N 2S 3E 4W
'''

items=[str(number)+direction  for number,direction zip(range(1,11),iter_cycl)]
# this time zip will go on because zip is basically an infinite iteration
'''
we can also do 'NSEW'*3 but this creates a sequence instead of a iterator
and is not as efficient as Iterator


'''

cycle_iter= CyclicIterator('NSWE');
[f'{i}{next(cycle_iter)}'  for i in range(1,11)];

# now we do the same with iter tools
iter_cycl= itertools.cycle('NSEW');
#now this is same as iterator generated by CyclicIterators.

class CyclicIterator:
	def __init__(self,iterable):
		self.iterable=iterable;
		self.iterator= iter(self.iterable);


	def __iter__(self):
	    return self;

	def __next__(self):
	    item= next(self.iterator)
	    return item;

cycle_iter = CyclicIterator('abc');

for i in range(5):
	print(i,next(cycle_iter))
# since iterator passed to CyclicIterator was in length 3 loop will return StopIteration Error
# after 3 iteration


# now we will make it into infinite iterator

class CyclicIterator:
	def __init__(self,iterable):
		self.iterable=iterable;
		self.iterator= iter(self.iterable);


	def __iter__(self):
	    return self;

	def __next__(self):
		try:
			item= next(self.iterator)
	        return item;
	    except StopIteration:
	    	self.iterable= iter(self.iterable)
	    

cycle_iter = CyclicIterator('abc');

for i in range(5):
	print(i,next(cycle_iter))

a b c None a b c None a b c None

class CyclicIterator:
	def __init__(self,iterable):
		self.iterable=iterable;
		self.iterator= iter(self.iterable);


	def __iter__(self):
	    return self;

	def __next__(self):
		try:
			item= next(self.iterator)
	    except StopIteration:
	    	self.iterable= iter(self.iterable)			
	    	item= next(self.iterator)
	    finally:
	    	return item;

cycle_iter = CyclicIterator('abc');

for i in range(5):
	print(i,next(cycle_iter))
